math: ture
markdown: kramdown
title: RSOME for Python
show_downloads: "true"
logo: rso_left.png
theme: jekyll-theme-minimal
navigation:
  - title: Home
    url: /
  - title: Quickstart Tutorial
    url: quickstart_tutorial
  - title: Robust Optimization with rsome
    url: ro_rsome
  - title: About
    url: about
